config/routes.rb
Rails.application.routes.draw do
  
  get '/students', to: 'students#index'
  get '/teachers', to: 'teachers#index'

  devise_scope :student do
    authenticated :student do
      resources :yearlevels do
        resources :topics do
          resources :worksheets do
            resources :items
            resources :answered_worksheets do
              resources :studentanswers
            end
          end
        end
      end
      root 'students#splash', as: :authenticated_student
    end
  end
  
  devise_scope :teacher do
    authenticated :teacher do
      resources :yearlevels do
        resources :topics do
          resources :worksheets do
            resources :items
          end
        end
      end
      root 'teachers#splash', as: :authenticated_teacher
    end
  end
  
  
  devise_scope :admin do
    authenticated :admin do
      resources :yearlevels do
        resources :topics do
          resources :worksheets do
            resources :items
          end
        end
      end
      resources :students, only: [:create, :deactivate, :update, :edit]
      resources :teachers, only: [:create, :deactivate, :update, :edit]

      get '/students/deactivate/' =>'students#deactivate'
      get '/students/edit' =>'students#edit'
      put '/students/update' =>'students#update'

      get '/teachers/deactivate/' =>'teachers#deactivate'
      get '/teachers/edit' =>'teachers#edit'
      put '/teachers/update' =>'teachers#update'

      root 'admins#index', as: :authenticated_admin
    end
  end
  
  devise_for :admins
    
  devise_for :teachers
    resources :teachers, except: :create
    resources :teachers_admin, :controller => 'teachers'
  devise_for :students
    resources :students, except: :create
    resources :students_admin, :controller => 'students'
    
    root 'publics#index'
    get '*unmatched_route', to: 'application#not_found'

end

app/models/worksheet.rb
class Worksheet < ActiveRecord::Base
    self.primary_key = 'id'
    belongs_to :topic
    belongs_to :yearlevel
    belongs_to :teacher
    belongs_to :admin
    has_many :items, dependent: :destroy
    has_many :answered_worksheets, dependent: :destroy
    has_many :studentanswers
    
    accepts_nested_attributes_for :items, :reject_if => :all_blank, :allow_destroy => true
    
    before_save :count_number

    validates :title, presence: true
    validates :directions, presence: true
    
    def count_number
        if !self.items.empty?
            self.items.each_with_index do |item, index|
              item.number = index + 1
            end
        end
    end
    
end

app/controllers/worksheets_controller.rb
class WorksheetsController < ApplicationController
  #before_action :not_for_student, only: [:new, :create]
  before_action :set_worksheet, except: [:new, :create]
  before_action :find_topic
  before_action :find_yearlevel
  
  def index

  end
  
  def show

  end

  def new
    @worksheet = Worksheet.new
  end
  
  def create
    @worksheet = @topic.worksheets.new(worksheet_params)
    @worksheet.yearlevel_id = @yearlevel.id
      if teacher_signed_in?
          @worksheet.teacher_id = current_teacher.id
      elsif admin_signed_in?
          @worksheet.admin_id = current_admin.id
      end
    
      if @worksheet.save
        redirect_to yearlevel_topic_path(@yearlevel, @topic), notice: 'Worksheet successfully saved'
      else
        render :new
      end
  end

  
  
  def edit
    @worksheet.items || @worksheet.build_items
  end
  
  def update
    @worksheet.items.each do |i|
      i.update(params.fetch(:item, {}))
    end
    @worksheet.update(worksheet_params)
      
    if @worksheet.save
      redirect_to yearlevel_topic_worksheet_path(@yearlevel, @topic, @worksheet), notice: 'Worksheet successfully saved'
    else
      render :edit
    end
  end
  
  def destroy
    @worksheet.destroy
    respond_to do |format|
      format.html { redirect_to yearlevel_topic_path(@yearlevel, @topic), notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    def set_worksheet
        @worksheet = Worksheet.find_by(id: params[:id])

        if @worksheet.nil?
          redirect_to root_path, alert: "Page not found"
        end
    end
    #finds year level of the topic
    def find_topic
        @topic = Topic.find(params[:topic_id])
    end 
    
    def find_yearlevel
      @yearlevel = Yearlevel.find(params[:yearlevel_id])
    end
    
    def worksheet_params
        params.require(:worksheet).permit(:title, :directions, items_attributes: [:id, :number, :question, :answer, :image, :remove_image])
    end
    
    
end

app/helpers/worksheets_helper.rb
module WorksheetsHelper
end

app/views/worksheets/_form.html.erb
<%= nested_form_for(@topic.worksheets.build) do |f| %>
  <% if @worksheet.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@worksheet.errors.count, "error") %> prohibited
        this worksheet from being saved:</h2>
    <ul>
    <% @worksheet.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
 
  <table class="table table-striped"> 
    <% @worksheet.items.each do |j| %>
        <tr> 
            <div class="field">
                <td>  <%= j.number %> </td>
                <td>  <%= f.text_field :question %> </td>
                <td>  <%= f.text_field :answer %> </td>
                <td>  </td>
            </div>
        </tr>
    <% end %>
          
</table>
<% end %>

app/views/worksheets/_item_fields.html.erb
<div class="nested-fields"> 
    <table class="table table-striped">
        <thead>
            <thead>
                <tr>
                    <th></th>
                    <th></th>
                    <th style="width:350px"></th>
                    <th style="width:60px"></th>
                </tr>
            </thead>
        </thead>
        <tbody>
            <tr>
                <td class="align-top">
                    <div class="form-group">
                        <%= f.label "Question" %>
                        <%= f.input :question,  as: :text, :label => false, input_html: {class:'form-control'} %>
                    </div>
                </td>
                <td class="align-top">
                    <div class="form-group">
                        <%= f.label "Answer" %>
                        <%= f.input :answer, as: :text, :label => false,input_html: {class:'form-control'}  %>
                    </div>
                </td>
                <td class="align-top">
                    <div class="form-group">
                        <p style="margin-bottom:8px;">Upload an image</p>
                        <div class="custom-file">

                            <%= f.label :image, "Image", class:'custom-file-label' %> <br>
                            <%= f.file_field :image,
                            class:'custom-file-input'  %></p>
                        </div>
                    </div>
                </td>
                <td><br>
                    <%= link_to_remove_association "Remove", f, class: "btn btn-danger" %>
                </td>
             </tr>
         </tbody>
     </table>
</div>

app/views/worksheets/edit.html.erb
<div class="bodynonav">
    <br>
<% unless admin_signed_in? || current_teacher.id == @worksheet.teacher_id %>
    <% redirect_to edit_yearlevel_topic_worksheet_path(@yearlevel, @topic, @worksheet) %>
<% end %>

<h1> <strong>WORKSHEETS</strong>  |  Edit Worksheet</h1>
    <ol class="arrows">
        <li><%= link_to "Home", root_path, method: :get %></li>
        <li><%= link_to "Worksheets", yearlevels_path, method: :get %></li>
        <li><%= link_to "Year level " + @topic.yearlevel.number.to_s, yearlevel_path(@topic.yearlevel), method: :get %></li>
        <li><%= link_to @topic.name, yearlevel_topic_path(@topic.yearlevel, @topic), method: :get %></li>
        <li><h2><%= @worksheet.title %></h2></li>
    </ol>
<br>
<% if @worksheet.errors.full_messages.count > 0 %>
  <div id="error_explanation" class="alert alert-danger" role="alert">
    <h4 class="text-error"><%= pluralize(@worksheet.errors.count, "error") %> prohibited this worksheet from being saved:</h4>
    <ul style="margin-bottom: 0">
    <% @worksheet.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= simple_nested_form_for @worksheet, url: yearlevel_topic_worksheet_path(@yearlevel, @topic, @worksheet), method: "put" do |f| %>

<div class="form-inputs">
    <p><strong><%= f.label "Worksheet Title" %></strong><br>
    <%= f.text_field :title, :value => @worksheet.title,:size => 135,  :label => false %></p>
    
    <p><strong><%= f.label "Directions" %></strong><br>
    <%= f.text_area :directions, :value => @worksheet.directions,  :cols => "135", :rows => "3",  :label => false  %></p>
</div>

<div class="items row worksheet">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Question</th>
                <th>Answers</th>
                <th style="width:350px"></th>
                <th style="width:60px"></th>
            </tr>
        </thead>
        <tbody>
            <%= f.simple_fields_for :items do |j| %>
                <% if !j.object.id.nil? %>
                    <tr>
                        <td class="align-top">
                            <%= j.text_area :question, :cols => "70", :rows => "3", :label => false,class:'form-control' %>
                            
                        </td>
                        <td class="align-top"><%= j.text_area :answer, :cols => "70", :rows => "3", :label => false,class:'form-control' %></td>
                        <td>
                            <% if j.object.image? %>
                              <%= image_tag j.object.image.url,class: 'img-fluid' %>
                              <%= j.label :remove_image %>
                              <%= j.check_box :remove_image %> 
                            <% else %>
                                <div class="custom-file">

                                    <%= j.label :image, "Image", class:'custom-file-label' %> <br>
                                    <%= j.file_field :image,
                                    class:'custom-file-input'  %></p>
                                </div>
                            <% end %>
                        </td>
                        <td class="align-middle">
                             <%= link_to 'Remove', yearlevel_topic_worksheet_item_path(@yearlevel, @topic, @worksheet, j.object.id), class: "btn btn-danger btn-lg", :method => :delete %>
                        </td>
                    </tr>
                <% end %>
            <% end %>
        </tbody>
    </table>
</div>



<div class="links" style="position:relative; margin-left:90%; margin-right:10%; ">
    <%= link_to_add_association 'Add Item', f, :items, class: "btn btn-success" %>
</div>
    <br>
<div class="form-actions"  style="position:relative; margin-left:90%; margin-right:10%; ">
    <%= f.button :submit, "Update Worksheet", class: "btn btn-primary btn-lg" %>
</div>
  <% end %>  
</div>

<script type="application/javascript">
    $(document).ready(function(){
        $(document).on('change','input[type="file"]',function (e) { 
            console.log($(this));
            var fileName = e.target.files[0].name;
            $(this).siblings('.custom-file-label').html(fileName);
        });
    });
    
</script>

app/views/worksheets/index.html.erb
<div class="row">
    <br>
    <h1> <strong>WORKSHEETS</strong>  |  Select Worksheet</h1>
    <ol class="arrows">
        <li><%= link_to "Home", root_path, method: :get %></li>
        <li><h2>Worksheets</h2></li>
    </ol>
    <br>
</div>
<div class="row">
    <table> 
        <thead> 
            <th> WORKHSHEET NAME </th>
            <th> DESCRIPTION </th>
            
        </thead>
        <% @worksheets.each do |i| %>
            <tr> 
                <td>  <%= i.number %> </td>
                <td> <%= i.description %> </td>
                <td> <%= link_to 'Select', worksheet_show_path(i), :class => 'navbar-link', method: :get %> </td>
            </tr>
        <% end %>
    </table>
</div>

app/views/worksheets/new.html.erb
<div class="row">
    <br>
    <h1> <strong>WORKSHEETS</strong>  |  Create Worksheet</h1>
    <ol class="arrows">
        <li><%= link_to "Home", root_path, method: :get %></li>
        <li><%= link_to "Worksheets", yearlevels_path, method: :get %></li>
        <li><%= link_to "Year level " + @topic.yearlevel.number.to_s, yearlevel_path(@topic.yearlevel), method: :get %></li>
        <li><%= link_to @topic.name, yearlevel_topic_path(@topic.yearlevel, @topic), method: :get %></li>
        <li><h2>New Worksheet</h2></li>
    </ol>
    <br>
    <br>
    <% if @worksheet.errors.full_messages.count > 0 %>
      <div id="error_explanation" class="alert alert-danger" role="alert">
        <h4 class="text-error"><%= pluralize(@worksheet.errors.count, "error") %> prohibited this worksheet from being saved:</h4>
        <ul style="margin-bottom: 0">
        <% @worksheet.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <%= simple_form_for @topic.worksheets.build, url: yearlevel_topic_worksheets_path(@yearlevel, @topic) do |f| %>

    <div class="form-inputs">
        <strong><p><%= f.label "Worksheet Title" %></strong><br>
        <%= f.text_field :title, :size => 135,  :label => false %></p>
        <strong><p><%= f.label "Directions" %></strong><br>
        <%= f.text_area :directions, :cols => "135", :rows => "3",  :label => false  %></p>
    </div>


    <div class="items row">
        <%= f.simple_fields_for :items do |item|  %>
            <%= render 'item_fields', :f => item %>
        <% end %>
    </div>
    <div class="links"  style="postion:relative; margin-left: 90%;">
        <%= link_to_add_association 'Add Item', f, :items, class: "btn btn-success btn-lg" %>
    </div>
    <br>
    <div class="form-actions" style="postion:realtive; margin-left: 90%; ">
        <%= f.button :submit, "Create", class: "btn btn-primary btn-lg"%>
    </div>
    <% end %>
</div>


<script type="application/javascript">
    $('input[type="file"]').change(function(e){
        var fileName = e.target.files[0].name;
        $(this).siblings('.custom-file-label').html(fileName);
    });
</script>

app/views/worksheets/show.html.erb
<div class="bodynonav">
<br>
<h1> <strong>WORKSHEETS</strong>  |  Show Worksheet</h1>
<ol class="arrows">
    <li><%= link_to "Home", root_path, method: :get %></li>
    <li><%= link_to "Worksheets", yearlevels_path, method: :get %></li>
    <li><%= link_to "Year level " + @topic.yearlevel.number.to_s, yearlevel_path(@topic.yearlevel), method: :get %></li>
    <li><%= link_to @topic.name, yearlevel_topic_path(@yearlevel, @topic), method: :get %></li>
    <li><h2><%= @worksheet.title %> </h2></li>
</ol>
<br>
<h1> <%= @worksheet.title %> </h1>
<strong>Directions:</strong> <%= @worksheet.directions %> 
<br>
<table class="table table-striped worksheet"> 
    <thead>
        <tr>
            <th style="width:20px;">No.</th>
            <th>Questions</th>
            <th>Answers</th>
        </tr>
    </thead>
    <tbody>
        <% @worksheet.items.each do |j| %>
            <tr> 
                <td class="align-top">  <%= j.number %> </td>
                <td class="align-top">  <%= j.question %> <br><%= if j.image.length > 0 then image_tag j.image.url, class: 'img-fluid' end %></td>
                <td class="align-top">  <%= j.answer %> </td>
            </tr>
        <% end %>
    </tbody>
          
</table>
<br>
<%= link_to 'Back', yearlevel_topic_path(@yearlevel, @topic), class: "btn btn-primary btn-lg", method: :get %> 