config/routes.rb
Rails.application.routes.draw do
  
  get '/students', to: 'students#index'
  get '/teachers', to: 'teachers#index'

  devise_scope :student do
    authenticated :student do
      resources :yearlevels do
        resources :topics do
          resources :worksheets do
            resources :items
            resources :answered_worksheets do
              resources :studentanswers
            end
          end
        end
      end
      root 'students#splash', as: :authenticated_student
    end
  end
  
  devise_scope :teacher do
    authenticated :teacher do
      resources :yearlevels do
        resources :topics do
          resources :worksheets do
            resources :items
          end
        end
      end
      root 'teachers#splash', as: :authenticated_teacher
    end
  end
  
  
  devise_scope :admin do
    authenticated :admin do
      resources :yearlevels do
        resources :topics do
          resources :worksheets do
            resources :items
          end
        end
      end
      resources :students, only: [:create, :deactivate, :update, :edit]
      resources :teachers, only: [:create, :deactivate, :update, :edit]

      get '/students/deactivate/' =>'students#deactivate'
      get '/students/edit' =>'students#edit'
      put '/students/update' =>'students#update'

      get '/teachers/deactivate/' =>'teachers#deactivate'
      get '/teachers/edit' =>'teachers#edit'
      put '/teachers/update' =>'teachers#update'

      root 'admins#index', as: :authenticated_admin
    end
  end
  
  devise_for :admins
    
  devise_for :teachers
    resources :teachers, except: :create
    resources :teachers_admin, :controller => 'teachers'
  devise_for :students
    resources :students, except: :create
    resources :students_admin, :controller => 'students'
    
    root 'publics#index'
    get '*unmatched_route', to: 'application#not_found'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
    self.primary_key = 'id'
    belongs_to :yearlevel

    has_many :worksheets
    has_many :items
    has_many :answered_worksheets
    has_many :studentanswers

    validates :name, presence: true
    validates :description, presence: true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
    before_action :set_topic, except: [:new, :create]
    before_action :find_yearlevel

    def index

    end
    def show

    end
    
    def new
        #@yearlevel = Yearlevel.find_by(id: params[:id])
        @topic = Topic.new
    end
    
    def create
        @topic = @yearlevel.topics.new(topic_params)
        if @topic.save
            redirect_to yearlevel_path(@yearlevel), notice: "Topic successfully added."
        else
            render :action=>'new'
        end
    end
    
    private
    
    def set_topic
        @topic = Topic.find_by(id: params[:id])
        if @topic.nil?
            redirect_to root_path, alert: "Page not found" and return
        end
    end
    
    def find_yearlevel
        @yearlevel = Yearlevel.find(params[:yearlevel_id])
        if @yearlevel.nil?
            redirect_to root_path, alert: "Page not found"
        end
    end 
    #finds year level of the topic
    
    
    def topic_params
        params.require(:topic).permit!
    end
    #passes on all parameters when creating topics
    
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/new.html.erb
<div class="bodynonav">
    <br>
<h1> <strong>WORKSHEETS</strong>  |  Create Topic</h1>
<br>
<br>
<% if @topic.errors.full_messages.count > 0 %>
  <div id="error_explanation" class="alert alert-danger" role="alert">
    <h4 class="text-error"><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h4>
    <ul style="margin-bottom: 0">
    <% @topic.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<fieldset>
    <%= simple_form_for @topic, url: yearlevel_topics_path(@yearlevel) do |f| %>
<div id="log-in" class="container">
<div class="col-6 col-sm-3">

<div class="form-inputs">
    <div class="row">
    <div class="input-field col s4">
    <p><%= f.label "Topic Title" %>
    <%= f.text_field :name %></p>
    </div>
    </div>
    <br>
    <div class="row">
    <div class="input-field col s4">
    <p><%= f.label "Description" %>
    <%= f.text_area :description, :size => "22" %></p>
    </div>
   </div>
      </div>
      <br>
</div>
<div class="row">
<div class="input-field col s4">
<div class="form-actions">
    <%= f.submit "Create", class: "btn btn-primary btn-lg" %>
</div>
</div>
</div>
<% end %>

</div>
</fieldset>

app/views/topics/show.html.erb
<br>
<h1><strong>WORKSHEETS</strong>  |  Select Worksheet</h1>
<ol class="arrows">
    <li><%= link_to "Home", root_path, method: :get %></li>
    <li><%= link_to "Worksheets", yearlevels_path, method: :get %></li>
    <li><%= link_to "Year level " + @topic.yearlevel.number.to_s, yearlevel_path(@topic.yearlevel), method: :get %></li>
    <li><h2><%= @topic.name %></h2></li>
</ol>
<br>
<div class="row">
    
    <% if for_teacher || for_admin %>
        <h4> <strong> YOUR CREATED WORKSHEETS </strong> </h4>
            <table class="table table-striped"> 
                <thead> 
                        <th>WORKSHEET NAME</th>
                        <th style="width:60px"></th>
                        <th style="width:60px"></th>
                        <th style="width:60px"></th>
                </thead>
                <tbody>
                    <% if for_teacher %>
                        <% own = Array.new %>
                        <% @topic.worksheets.each do |i| %>
                            <% if current_teacher.id == i.teacher_id %>
                                <% own.push(i) %>
                            <% end %>
                        <% end %>
                            <% if own.count != 0 %>
                                <% own.each do |i| %>
                                    <tr> 
                                        <td>  <%= i.title %> </td>
                                        <td> <%= link_to 'View', yearlevel_topic_worksheet_path(@yearlevel, @topic, i), class: "btn btn-primary btn-lg", method: :get %> </td>
                                        <td> <%= link_to 'Edit', edit_yearlevel_topic_worksheet_path(@yearlevel, @topic, i), class: "btn btn-warning btn-lg", method: :get %></td>
                                        <td> <%= link_to 'Delete', yearlevel_topic_worksheet_path(@yearlevel, @topic, i), class: "btn btn-danger btn-lg", :method => :delete, :data => {:confirm => 'Are you sure you want to delete this workheet?'} %> </td>
                                    </tr>
                                <% end %>
                            <% else %>
                                <tr>
                                    <td colspan="4" class="text-center"><h5>You have no worksheets yet.</h5> </td>
                                </tr>
                            <% end %>
                    <% else %>
                        <% own = Array.new %>
                        <% @topic.worksheets.each do |i| %>
                            <% if i.admin_id != nil %>
                                <% own.push(i) %>
                            <% end %>
                        <% end %>
                        <% if own.count != 0 %>
                            <% own.each do |i| %>
                                <tr> 
                                    <td>  <%= i.title %> </td>
                                    <td> <%= link_to 'View', yearlevel_topic_worksheet_path(@yearlevel, @topic, i), class: "btn btn-primary btn-lg", method: :get %> </td>
                                    <td> <%= link_to 'Edit', edit_yearlevel_topic_worksheet_path(@yearlevel, @topic, i), class: "btn btn-warning btn-lg", method: :get %></td>
                                    <td> <%= link_to 'Delete', yearlevel_topic_worksheet_path(@yearlevel, @topic, i), class: "btn btn-danger btn-lg", :method => :delete, :data => {:confirm => 'Are you sure you want to delete this workheet?'} %> </td>
                                </tr>
                            <% end %>
                        <% else %>
                            <tr>
                                <td colspan="4" class="text-center"><h5>You have no worksheets yet.</h5> </td>
                            </tr>
                        <% end %>
                    <% end %>
                </tbody>
            </table>
        <br>
        <h4 style="margin-top:30px;"> <strong> OTHER WORKSHEETS </strong> </h4>
            <table class="table table-striped"> 
                <thead> 
                        <th>WORKSHEET NAME</th>
                        <th>CREATED BY</th>
                        <th></th>
                        <th></th>
                        <th></th>
                </thead>
                <tbody>
                    <% if for_teacher %>
                        <% own = Array.new %>
                        <% @topic.worksheets.each do |i| %>
                            <% if current_teacher.id != i.teacher_id %>
                                <% own.push(i) %>
                            <% end %>
                        <% end %>
                        <% if own.count != 0 %>
                            <% own.each do |i| %>
                                <tr> 
                                    <td>  <%= i.title %> </td>
                                    <td>
                                         <% if i.teacher_id = "" %>
                                            Admin
                                         <% else %>
                                            Teacher ID # <%= i.teacher_id %>
                                         <% end %>
                                    </td>
                                    <td> <%= link_to 'View', yearlevel_topic_worksheet_path(@yearlevel, @topic, i), class: "btn btn-primary btn-lg" %> </td>
                                    <td> </td>
                                    <td> </td>
                                </tr>
                            <% end %>
                        <% else %> 
                            <tr>
                                <td colspan="5" class="text-center"><h5>There are no other worksheets.</h5> </td>
                            </tr>
                        <% end %>
                    <% else %>
                        <% own = Array.new %>
                        <% @topic.worksheets.each do |i| %>
                            <% if i.admin_id == nil %>
                                <% own.push(i) %>
                            <% end %>
                        <% end %>
                        <% if own.count != 0 %>
                            <% own.each do |i| %>
                                <tr>
                                    <td>  <%= i.title %> </td>
                                    <td> Teacher ID # <%= i.teacher_id %> </td>
                                    <td> <%= link_to 'View', yearlevel_topic_worksheet_path(@yearlevel, @topic, i), class: "btn btn-primary btn-lg", method: :get %> </td>
                                    <td> <%= link_to 'Edit', edit_yearlevel_topic_worksheet_path(@yearlevel, @topic, i), class: "btn btn-warning btn-lg", method: :get %></td>
                                    <td> <%= link_to 'Delete', yearlevel_topic_worksheet_path(@yearlevel, @topic, i), class: "btn btn-danger btn-lg", :method => :delete, :data => {:confirm => 'Are you sure you want to delete this workheet?'} %> </td>
                                </tr>
                            <% end %>
                        <% else %>
                            <tr>
                                <td colspan="5" class="text-center"><h5>There are no other worksheets.</h5> </td>
                            </tr>
                        <% end %>
                        
                    <% end %>
                </tbody>
            </table>
        
        <%= link_to 'Create New Worksheet', new_yearlevel_topic_worksheet_path(@yearlevel, @topic), class: "btn btn-primary btn-lg", method: :get %>
            
    <% else %>
        <table class="table table-striped"> 
        <thead> 
                <th>  WORKSHEET NAME </th>
                <th>  DIRECTIONS </th>
                <th>             </th>
            
        </thead>
        <tbody>
            <% @topic.worksheets.each do |i| %>
                    <tr> 
                        <td>  <%= i.title %> </td>
                        <td>  <%= i.directions %> </td>
                        <td> <%= link_to 'Answer', new_yearlevel_topic_worksheet_answered_worksheet_path(@yearlevel, @topic, i), class: "btn btn-primary btn-lg", method: :get %></td>
                    </tr>
            <% end %>
         </tbody>
        </table>
    <% end %>
</div>

                                                            