config/routes.rb
Rails.application.routes.draw do
  
  get '/students', to: 'students#index'
  get '/teachers', to: 'teachers#index'

  devise_scope :student do
    authenticated :student do
      resources :yearlevels do
        resources :topics do
          resources :worksheets do
            resources :items
            resources :answered_worksheets do
              resources :studentanswers
            end
          end
        end
      end
      root 'students#splash', as: :authenticated_student
    end
  end
  
  devise_scope :teacher do
    authenticated :teacher do
      resources :yearlevels do
        resources :topics do
          resources :worksheets do
            resources :items
          end
        end
      end
      root 'teachers#splash', as: :authenticated_teacher
    end
  end
  
  
  devise_scope :admin do
    authenticated :admin do
      resources :yearlevels do
        resources :topics do
          resources :worksheets do
            resources :items
          end
        end
      end
      resources :students, only: [:create, :deactivate, :update, :edit]
      resources :teachers, only: [:create, :deactivate, :update, :edit]

      get '/students/deactivate/' =>'students#deactivate'
      get '/students/edit' =>'students#edit'
      put '/students/update' =>'students#update'

      get '/teachers/deactivate/' =>'teachers#deactivate'
      get '/teachers/edit' =>'teachers#edit'
      put '/teachers/update' =>'teachers#update'

      root 'admins#index', as: :authenticated_admin
    end
  end
  
  devise_for :admins
    
  devise_for :teachers
    resources :teachers, except: :create
    resources :teachers_admin, :controller => 'teachers'
  devise_for :students
    resources :students, except: :create
    resources :students_admin, :controller => 'students'
    
    root 'publics#index'
    get '*unmatched_route', to: 'application#not_found'

end

app/models/answered_worksheet.rb
class AnsweredWorksheet < ActiveRecord::Base
    
    self.primary_key ='id'
    belongs_to :topic
    belongs_to :yearlevel
    belongs_to :worksheet
    belongs_to :student
   # has_many :items
    has_many :studentanswers, dependent: :destroy
    #attr_accessor :title
    #attr_accessor :directions
    #attr_accessor :studentinput
    
    accepts_nested_attributes_for :studentanswers, :reject_if => :all_blank, :allow_destroy => true
    
end

app/controllers/answered_worksheets_controller.rb
class AnsweredWorksheetsController < ApplicationController
  before_action :set_answered_worksheet, only: [:show, :edit, :update, :destroy]
  before_action :find_topic
  before_action :find_yearlevel
  before_action :find_worksheet
  before_action :compute_score, only: :save
  
  
  def index
    
  end

  def show
    @questionList = Array.new
    @numberList = Array.new
    @answerList = Array.new
    @studentanswerList = Array.new
    
    @worksheet.items.each do |j|
      @questionList.push(j.question)
      @answerList.push(j.answer)
      @numberList << j.number
    end
    @answered_worksheet.studentanswers.each do |k|
      @studentanswerList << k.studentinput
    end
    
      
  end

  def new
    @answered_worksheet = AnsweredWorksheet.new
    
    #@answered_worksheet.studentanswers.build
  
  end

  def edit
  end

  def create
    @answered_worksheet = @worksheet.answered_worksheets.new(answered_worksheet_params)
    #raise params.inspect
    
    @answered_worksheet.yearlevel_id = @yearlevel.id
    @answered_worksheet.topic_id = @topic.id
    @answered_worksheet.student_id = current_student.id
    @answered_worksheet.hps = @worksheet.items.count
    
    score = 0
        answerkey = Array.new
        inputs = Array.new
           
            for x in @worksheet.items.each do
               answerkey.push(x.answer)
            end
            
            for y in @answered_worksheet.studentanswers.each do
                inputs.push(y.studentinput)
            end
            
              answerkey.zip(inputs) do |answer, input|
                  if answer == input
                      score += 1
                  end
              end
       @answered_worksheet.correctanswer = score
    
    
    
    
    if @answered_worksheet.save
      redirect_to yearlevel_topic_worksheet_answered_worksheet_path(@yearlevel, @topic, @worksheet, @answered_worksheet, @student)
    else
      render :new
    end
    
  end

  def update
    respond_to do |format|
      if @answered_worksheet.update(answered_worksheet_params)
        format.html { redirect_to @answered_worksheet, notice: 'Answered worksheet was successfully updated.' }
        format.json { render :show, status: :ok, location: @answered_worksheet }
      else
        format.html { render :edit }
        format.json { render json: @answered_worksheet.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @answered_worksheet.destroy
    respond_to do |format|
      format.html { redirect_to answered_worksheets_url, notice: 'Answered worksheet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  
  
  private
    def set_answered_worksheet
      @answered_worksheet = AnsweredWorksheet.find_by(id: params[:id])
    end
    
    def find_topic
        @topic = Topic.find(params[:topic_id])
    end 
    
    def find_yearlevel
      @yearlevel = Yearlevel.find(params[:yearlevel_id])
    end
    
    def find_worksheet
      @worksheet = Worksheet.find(params[:worksheet_id])
    end
    
    def find_student
      @student = current_user
    end

    def answered_worksheet_params
      params.require(:answered_worksheet).permit(:correctanswer, :hps, :dateanswered, studentanswers_attributes: [:studentinput])
    end
    
    def student_answer_params
      params.require()
    end
    
    
    
end

app/helpers/answered_worksheets_helper.rb
module AnsweredWorksheetsHelper
end

app/views/answered_worksheets/_form.html.erb
<%= simple_form_for(@answered_worksheet) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/answered_worksheets/_studentanswer_fields.html.erb
    <%= f.label "Answer" %>
    <%= f.input :studentinput,  as: :text, :label => false %>

app/views/answered_worksheets/edit.html.erb
<h1>Editing Answered Worksheet</h1>

<%= render 'form' %>

<%= link_to 'Show', @answered_worksheet %> |
<%= link_to 'Back', answered_worksheets_path %>

app/views/answered_worksheets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Answered Worksheets</h1>
<br>
<table>
  <thead>
    <tr>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @answered_worksheets.each do |answered_worksheet| %>
      <tr>
        <td><%= link_to 'Show', answered_worksheet %></td>
        <td><%= link_to 'Edit', edit_answered_worksheet_path(answered_worksheet) %></td>
        <td><%= link_to 'Destroy', answered_worksheet, method: :delete, data: { confirm: 'Are you sure you want to delete this worksheet?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answered worksheet', new_answered_worksheet_path %>

app/views/answered_worksheets/new.html.erb
<div class="bodynonav">
<br>
<h1> <strong>WORKSHEETS</strong>  |  Answer Worksheet</h1>
<ol class="arrows">
    <li><%= link_to "Home", root_path, method: :get %></li>
    <li><%= link_to "Worksheets", yearlevels_path, method: :get %></li>
    <li><%= link_to "Year level " + @topic.yearlevel.number.to_s, yearlevel_path(@topic.yearlevel), method: :get %></li>
    <li><%= link_to @topic.name, yearlevel_topic_path(@yearlevel, @topic), method: :get %></li>
    <li><h2><%= @worksheet.title %> </h2></li>
</ol>
<br>

<h1> <%= @worksheet.title %> </h1>
<h6> Directions: <%= @worksheet.directions %></h6>
<br>
<%= simple_form_for @worksheet.answered_worksheets.build, url: yearlevel_topic_worksheet_answered_worksheets_path(@yearlevel, @topic, @worksheet) do |f| %>

<table class="table table-striped"> 
    <th>No.</th>
    <th>Questions</th>
    <th>Answers</th>
   
    <% @worksheet.items.each do |j| %>
        <tr> 
            <td class="align-top">  <%= j.number %> </td>
            <td class="align-top">  <%= j.question %> 
                <br>
                <% if j.image? %>
                  <%= image_tag j.image.url,class: 'img-fluid' %>
                <% end %>
            </td>
            <%= f.fields_for :studentanswers, @answered_worksheet.studentanswers.build do |studentanswer| %>
                <td class="align-top">
                    <%= studentanswer.input :studentinput,  as: :text, :label => false %>
                </td>
            <% end %>
        </tr>
    <% end %>
    
</table>

<div class="form-actions">
    <%= f.button :submit, "Finish Worksheet", class: "btn btn-primary btn-lg" %>
</div>

<% end %>


<%#= render 'form' %>

<%#= link_to 'Back', answered_worksheets_path %>

app/views/answered_worksheets/show.html.erb
<div class="bodynonav">
<br>
<h1> <strong>WORKSHEETS</strong>  |  Worksheet Result</h1>
<ol class="arrows">
    <li><%= link_to "Home", root_path, method: :get %></li>
    <li><%= link_to "Worksheets", yearlevels_path, method: :get %></li>
    <li><%= link_to "Year level " + @topic.yearlevel.number.to_s, yearlevel_path(@topic.yearlevel), method: :get %></li>
    <li><%= link_to @topic.name, yearlevel_topic_path(@yearlevel, @topic), method: :get %></li>
    <li><h2><%= @worksheet.title %> </h2></li>
</ol>
<br>
    
<%= simple_form_for @worksheet.answered_worksheets.build, url: yearlevel_topic_worksheet_answered_worksheets_path(@yearlevel, @topic, @worksheet) do |f| %>

<div class="form-inputs">
<div class="container">
<div class="row">
    <div class="col-10">
    <h2><%= @worksheet.title %> </h2></p>

     <strong>Directions:</strong>
     </strong> <%= @worksheet.directions %> </p> 
     </div>
     <div class="col-2">
    <div style="border: black 2px solid; width:150px; length:100px;">
        <br>
    <center><h3>SCORE</h3><h5><%= @answered_worksheet.correctanswer %> / <%= @answered_worksheet.hps %></h5> </center>
    <br>
    </div>
    </div>
</div>
</div>
</div>

<br>
<table class="table table-striped"> 
    <th>No.</th>
    <th>Questions</th>
    <th>Answers</th>
    <th>Correct Answer</th>
    <% @studentanswerList.zip(@answerList, @questionList, @numberList) do |l, k, j, i| %>
        <% if l == k %>
            <tr style="background-color:#66C866;">
        <% else %> 
            <tr style="background-color:#FF7074;">
        <% end %>
                <td>  <%= i %> </td>
                <td>  <%= j %> </td>
                <td> <%= l %> </td>
                <td> <%= k %> </td>
            </tr>
    <% end %>
</table>

<% end %>
<br>
<%= link_to 'Back', yearlevel_topic_path(@yearlevel, @topic), class: "btn btn-primary btn-lg" %>
</div>