config/routes.rb
Rails.application.routes.draw do
  
  get '/students', to: 'students#index'
  get '/teachers', to: 'teachers#index'

  devise_scope :student do
    authenticated :student do
      resources :yearlevels do
        resources :topics do
          resources :worksheets do
            resources :items
            resources :answered_worksheets do
              resources :studentanswers
            end
          end
        end
      end
      root 'students#splash', as: :authenticated_student
    end
  end
  
  devise_scope :teacher do
    authenticated :teacher do
      resources :yearlevels do
        resources :topics do
          resources :worksheets do
            resources :items
          end
        end
      end
      root 'teachers#splash', as: :authenticated_teacher
    end
  end
  
  
  devise_scope :admin do
    authenticated :admin do
      resources :yearlevels do
        resources :topics do
          resources :worksheets do
            resources :items
          end
        end
      end
      resources :students, only: [:create, :deactivate, :update, :edit]
      resources :teachers, only: [:create, :deactivate, :update, :edit]

      get '/students/deactivate/' =>'students#deactivate'
      get '/students/edit' =>'students#edit'
      put '/students/update' =>'students#update'

      get '/teachers/deactivate/' =>'teachers#deactivate'
      get '/teachers/edit' =>'teachers#edit'
      put '/teachers/update' =>'teachers#update'

      root 'admins#index', as: :authenticated_admin
    end
  end
  
  devise_for :admins
    
  devise_for :teachers
    resources :teachers, except: :create
    resources :teachers_admin, :controller => 'teachers'
  devise_for :students
    resources :students, except: :create
    resources :students_admin, :controller => 'students'
    
    root 'publics#index'
    get '*unmatched_route', to: 'application#not_found'

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :pusername, uniqueness: true, presence: true, length: { maximum: 30 }
  validates :firstname, presence: true
  validates :lastname, presence: true 
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         authentication_keys: [:pusername]
         
  has_many :worksheets
  
  # for better-looking error messages
  HUMANIZED_ATTRIBUTES = {
    :pusername => "Username",
    :firstname => "First name",
    :lastname => "Last name",
  }

  def self.human_attribute_name(attr, options = {})
    HUMANIZED_ATTRIBUTES[attr.to_sym] || super
  end

  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
    # before_action :set_teacher, only: [:update, :edit, :destroy, :show]
    #before_filter :authorize_admin, only: :create
    
    def index
        @teachers = Teacher.all
    end
    
    def show
        @teacher = Teacher.find params[:susername]
    end
    
    def new
        @teacher = Teacher.new
    end

    def edit   
        @teacher = Teacher.find_by(id: params[:teacher])
        if @teacher.nil?
            redirect_to teachers_path, alert: "Teacher not found." and return
        else
            render "teachers/edit" 
        end
    end

    def destroy
        @teacher = Teacher.find_by(id: params[:teacher][:id])
        if @teacher.nil?
            redirect_to teachers_path, alert: "Teacher not found." and return
        end

        if @teacher.status == true
          @teacher.status = false
        else
          @teacher.status = true
        end
        
        if @teacher.save
            redirect_to teachers_path, notice: "Teacher successfully updated."
        end
    end

    def update
        @teacher = Teacher.find_by(id: params[:teacher][:id])
        if @teacher.nil?
            redirect_to teachers_path, alert: "Teacher not found." and return
        else 
            @teacher.pusername = params[:teacher][:pusername]
            @teacher.firstname = params[:teacher][:firstname]
            @teacher.lastname = params[:teacher][:lastname]
            @teacher.save!

            redirect_to teachers_path, notice: "Teacher successfully edited."
        end
    end
    
    def create
        @teacher = Teacher.new(teacher_params)
        if @teacher.save
            redirect_to teachers_path, notice: "Teacher successfully added."
        else
            redirect_to :back, flash: {errors: @teacher.errors.full_messages}
        end
    end
    
    private
    def teacher_params
      params.require(:teacher).permit(:pusername, :firstname, :lastname, :password, :salt, :encrypted_password, :password_confirmation)
    end
    
    def set_teacher
      @teacher = Teacher.find_by(id: params[:id])
      if @teacher.nil?
            redirect_to teachers_path, alert: "Teacher not found." and return
        end
    end
    
    def authorize_admin
    return unless !current_user.admin?
    redirect_to root_path, alert: 'Admins only!'
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/edit.html.erb
<br>
<ol class="arrows">
    <li><%= link_to "Home", root_path, method: :get %></li>
    <li><%= link_to "Teachers", teachers_path, method: :get %></li>
</ol>
<h1>Edit Teacher Account</h1>
<div class="row">
  <div class="col-xs-12 col-md-6">
    <br><br>
    <%= simple_form_for(@teacher, as: :teacher, url: teachers_update_path, html: { method: :put }) do |f| %>
        <%= f.error_notification %>
        <input type="hidden" name="teacher[id]" value="<%= @teacher.id %>">
        <div class="form-group">
          <%= f.label :susername, "User name:" %>
          <%= f.text_field :pusername, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :firstname, "First name:" %>
          <%= f.text_field :firstname, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :lastname, "Last name:" %>
          <%= f.text_field :lastname, class: 'form-control' %>
        </div>
          <%# if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
            <!-- <p>Currently waiting confirmation for: <%#= resource.unconfirmed_email %></p> -->
          <%# end %>

          <%# f.input :password, autocomplete: "off", hint: "leave it blank if you don't want to change it", required: false %>
          <%# f.input :password_confirmation, required: false %>
          <%# f.input :current_password, hint: "we need your current password to confirm your changes", required: true %>
        <br>
        <div class="form-actions">
          <%= f.button :submit, "Update",class: 'btn btn-primary' %><%= link_to "Back", teachers_path, class: 'btn btn-ghost'%>
        </div>
      <% end %>
  </div>
</div>
<!-- <p>Unhappy? <%# link_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete %></p> -->

app/views/teachers/index.html.erb
<br>
<h1> <strong>ACCOUNTS</strong>  |  Teacher Accounts</h1>
<ol class="arrows">
    <li><%= link_to "Home", root_path, method: :get %></li>
    <li><h2>Accounts</h2></li>
</ol>
<div class="row">
    <div class="col-lg-12">
        <% if @teachers.count > 0 %>
        <table class="table table-striped table-responsive-md">
            <thead>
                <tr>
                    <th>User Name</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Status</th>
                    <th style="width:80px"></th>
                    <th style="width:40px"></th>
                </tr>
            </thead>
            <tbody>
                <% @teachers.each do |p| %>
                    <tr>
                        <td><%= p.pusername %></td>
                        <td><%= p.firstname %></td>
                        <td><%= p.lastname %></td>
                        <td><%= if p.status == true then "Active" else "Inactive" end %></td>
                        
                        <td><% if p.status %>
                            <%= simple_form_for(p, as: :teacher, url: url_for(:controller => 'teachers', :action => 'deactivate'), html: { method: :delete }) do |f| %>
                                <input type="hidden" name="teacher[id]" value="<%= p.id %>">
                                <button class="btn btn-danger" onclick="confirm('Are you sure you want to deactivate?')">Deactivate</button>
                            <% end %>
                        <% else %>
                            <%= simple_form_for(p, as: :teacher, url: url_for(:controller => 'teachers', :action => 'deactivate'), html: { method: :delete }) do |f| %>
                                <input type="hidden" name="teacher[id]" value="<%= p.id %>">
                                <button class="btn btn-success" onclick="confirm('Are you sure you want to activate?')">Activate</button>
                            <% end %>
                        <% end %>
                        </td> 
                        
                        <td><%= link_to "Edit",  teachers_edit_path(teacher: p.id), class: 'btn btn-warning'  %> </td>
                    </tr>
                <% end %>
            </tbody>
        </table> 
        <%= link_to "Create teacher", new_teacher_registration_path, class: "btn btn-primary btn-lg", style: 'margin-bottom:20px;', method: :get %>
        <% else %>
            <div class="text-center">
                <h2 class="text-regular text-center">No accounts available</h2>
                <br>
                <%= link_to "Create a teacher account", new_teacher_registration_path, class: "btn btn-primary btn-lg", style: 'margin-bottom:20px;' %>
            </div>
        <% end %>
    </div>
</div>

app/views/teachers/splash.html.erb
<div class="container">
<div class="row">
<div class="col-6">
    <br>
    <br>
<center>
    <h3>WELCOME TO KINETIC MATH</h3>
    <br>
    <br>
    <img src="https://i.imgur.com/t9GSmYd.png"> &nbsp
    <img src="https://i.imgur.com/1ruEnJU.png"> &nbsp
    <img src="https://i.imgur.com/K2fAlIi.png"> &nbsp
    <br>
    <br>
    <br>
    <p class="splash">
               Kinetic Math is your TRUE Math Enrichment center. 
        It offers energizing and engaging learning activities which help students develop
        numberical fluency, creativity, critical thinking and problem solving skills while enjoying math.
        <br>
        <br>
               The program's progression from a learning task to guided practice
        to independent practice not only boosts the child's confidence and
        fosters the child's interest in Math but also enables the child to develop a 
        deeper understanding of Math.
    </p>
</center>
</div>
<div class="col-6">
    <br>
    <br>
    <center>
    <h3>HOW TO CREATE WORKSHEETS?</h3>
    </center>
    <br>
    <br>
    <img src="https://i.imgur.com/m9UZOAQ.png" hspace="10px" style="float:left;"> 
    <br>
    <h6>Go to the "Worksheets" tab above or click the "Create Worksheets" button below.</h6>
    <br>
    <br>
    <img src="https://i.imgur.com/KqgvDkA.png" hspace="10px" style="float:left;"> 
    <br>
    <h6>Choose the year level of the worksheet you will create by clicking the "Select" button beside the year level.</h6>
    <br>
    <br>
    <img src="https://i.imgur.com/uK2ejln.png" hspace="10px" style="float:left;"> 
    <h6>Choose the topic of the worksheet you will create by clicking the "Select" button beside it. If the topic your worksheet falls under is not yet existent, you can create a new topic by clicking the "Create Topic" button.</h6>
    <br>
    <img src="https://i.imgur.com/SZeQOCD.png" hspace="10px" style="float:left;"> 
    <br>
    <h6>You can now Edit and Delete worksheet you've created or Create new worksheets on the worksheet page.</h6>
    <br>
    <br>
    <div class="button">
   <%= link_to "Create Worksheets", yearlevels_path, class: "btn btn-primary btn-lg" %>
    </div>
</div>


</div>
</div>  
            